export let countryComparison = {
  "2014": {
    "Participating countries and territories": [
      "Albania",
      "Armenia",
      "Bangladesh",
      "Benin",
      "Burkina Faso",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Cabo Verde",
      "Democratic Republic of the Congo",
      "Congo",
      "Côte d’Ivoire",
      "Egypt",
      "El Salvador",
      "Ethiopia",
      "Guatemala",
      "Honduras",
      "Jamaica",
      "Kenya",
      "Kiribati",
      "Kosovo",
      "Lesotho",
      "Madagascar",
      "Malawi",
      "Mali",
      "Marshall Islands",
      "Micronesia",
      "Moldova",
      "Mozambique",
      "Nauru",
      "Nepal",
      "Niger",
      "Niue",
      "Palau",
      "Peru",
      "Philippines",
      "Rwanda",
      "Samoa",
      "Senegal",
      "Sudan",
      "Tajikistan",
      "Tanzania",
      "Timor-Leste",
      "Togo",
      "Viet Nam",
      "West Bank and Gaza Strip",
      "Global Average"
    ],
    "Development partners included in the monitoring round": [
      "Algeria",
      "Australia",
      "Austria",
      "Belgium",
      "Canada",
      "China",
      "Chinese Taipei",
      "Czech Republic",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Italy",
      "Japan",
      "Republic of Korea",
      "Kuwait",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "Saudi Arabia",
      "Slovak Republic",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Turkey",
      "United Arab Emirates",
      "United Kingdom",
      "United States"
    ]
  },
  "2016": {
    "Participating countries and territories": [
      "Afghanistan",
      "Albania",
      "Angola",
      "Armenia",
      "Bangladesh",
      "Belarus",
      "Benin",
      "Bhutan",
      "Bolivia",
      "Burkina Faso",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Colombia",
      "Comoros",
      "Congo",
      "Cook Islands",
      "Costa Rica",
      "Côte d'Ivoire",
      "Democratic Republic of the Congo",
      "Dominican Republic",
      "Egypt",
      "El Salvador",
      "Ethiopia",
      "Fiji",
      "Gabon",
      "Gambia",
      "Guatemala",
      "Guinea",
      "Honduras",
      "Kenya",
      "Kiribati",
      "Kosovo",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Liberia",
      "Madagascar",
      "Malawi",
      "Mali",
      "Marshall Islands",
      "Mauritania",
      "Micronesia",
      "Moldova",
      "Mongolia",
      "Mozambique",
      "Myanmar",
      "Nauru",
      "Nepal",
      "Niger",
      "Nigeria",
      "Niue",
      "Pakistan",
      "Palau",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Rwanda",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "Sao Tome and Principe",
      "Senegal",
      "Sierra Leone",
      "Solomon Islands",
      "Somalia",
      "South Sudan",
      "Sudan",
      "Tajikistan",
      "Tanzania",
      "Timor-Leste",
      "Togo",
      "Tonga",
      "Tuvalu",
      "Uganda",
      "Uruguay",
      "Vanuatu",
      "Viet Nam",
      "Yemen",
      "Zimbabwe",
      "Global Average"
    ],
    "Development partners included in the monitoring round": [
      "Angola",
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Canada",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Congo",
      "Czech Republic",
      "Denmark",
      "El Salvador",
      "Equatorial Guinea",
      "Finland",
      "France",
      "Gabon",
      "Germany",
      "Iceland",
      "India",
      "Iran",
      "Iraq",
      "Ireland",
      "Italy",
      "Japan",
      "Republic of Korea",
      "Kuwait",
      "Lithuania",
      "Luxembourg",
      "Mexico",
      "Monaco",
      "Morocco",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Panama",
      "Papua New Guinea",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saudi Arabia",
      "Slovak Republic",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "Turkey",
      "United Arab Emirates",
      "United Kingdom",
      "United States"
    ]
  },
  "Aggregate": {
    "Region": [
      "Africa",
      "East Asia",
      "Eastern Europe and Central Asia",
      "Latin America and the Caribbean",
      "Pacific",
      "South Asia"
    ],
    "Income Group": [
      "Low income",
      "Lower middle income",
      "Upper middle income"
    ],
    "Country Context": [
      "Least Developed Countries (LDC) ",
      "Small Island Developing States (SIDS)"
    ]
  }
};