export let countryComparison = {
  "2010": {
    "Partner Country": [
      "Afghanistan",
      "Albania",
      "Angola",
      "Armenia",
      "Bangladesh",
      "Belarus",
      "Benin",
      "Bhutan",
      "Bolivia",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Colombia",
      "Comoros",
      "Congo",
      "Cook Islands",
      "Costa Rica",
      "Democratic Republic of the Congo",
      "Dominican Republic",
      "Egypt",
      "El Salvador",
      "Ethiopia",
      "Fiji",
      "Gabon",
      "Gambia",
      "Guatemala",
      "Guinea",
      "Honduras",
      "Ivory Coast",
      "Kenya",
      "Kiribati",
      "Kosovo",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Liberia",
      "Madagascar",
      "Malawi",
      "Mali",
      "Marshall Islands",
      "Mauritania",
      "Micronesia",
      "Mongolia",
      "Mozambique",
      "Myanmar",
      "Nauru",
      "Nepal",
      "Niger",
      "Nigeria",
      "Niue",
      "Pakistan",
      "Palau",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Republic of Moldova",
      "Rwanda",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "Sao Tome and Principe",
      "Senegal",
      "Sierra Leone",
      "Solomon Islands",
      "Somalia",
      "South Sudan",
      "Sudan",
      "Tajikistan",
      "Timor-Leste",
      "Togo",
      "Tonga",
      "Tuvalu",
      "Uganda",
      "United Republic of Tanzania",
      "Uruguay",
      "Vanuatu",
      "Vietnam",
      "Yemen",
      "Zimbabwe"
    ],
    "Development Partner": [
      "Angola",
      "Colombia",
      "Congo",
      "El Salvador",
      "Gabon",
      "Papua New Guinea",
      "Canada",
      "United States of America"
    ]
  },
  "2014": {
    "Partner Country": [
      "Albania",
      "Armenia",
      "Bangladesh",
      "Benin",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Congo",
      "Democratic Republic of the Congo",
      "Egypt",
      "El Salvador",
      "Ethiopia",
      "Guatemala",
      "Honduras",
      "Ivory Coast",
      "Kenya",
      "Kiribati",
      "Kosovo",
      "Madagascar",
      "Malawi",
      "Mali",
      "Marshall Islands",
      "Micronesia",
      "Mozambique",
      "Nauru",
      "Nepal",
      "Niger",
      "Niue",
      "Palau",
      "Peru",
      "Philippines",
      "Republic of Moldova",
      "Rwanda",
      "Samoa",
      "Senegal",
      "Sudan",
      "Tajikistan",
      "Timor-Leste",
      "Togo",
      "United Republic of Tanzania",
      "Vietnam"
    ],
    "Development Partner": [
      "Congo",
      "El Salvador",
      "Canada",
      "United States of America",
      "United Kingdom of Great Britain and Northern Ireland",
      "Germany",
      "Spain",
      "New Zealand",
      "France",
      "Slovakia",
      "Norway",
      "Republic of Korea",
      "Finland",
      "Sweden",
      "Australia",
      "Portugal",
      "Japan",
      "Luxembourg",
      "Ireland",
      "Italy",
      "Czech Republic",
      "Belgium",
      "Switzerland",
      "Netherlands",
      "Austria",
      "Denmark",
      "Greece"
    ]
  },
  "2016": {
    "Partner Country": [
      "Afghanistan",
      "Albania",
      "Angola",
      "Armenia",
      "Bangladesh",
      "Belarus",
      "Benin",
      "Bhutan",
      "Bolivia",
      "Burkina Faso",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Colombia",
      "Comoros",
      "Congo",
      "Cook Islands",
      "Costa Rica",
      "Democratic Republic of the Congo",
      "Dominican Republic",
      "Egypt",
      "El Salvador",
      "Ethiopia",
      "Fiji",
      "Gabon",
      "Gambia",
      "Guatemala",
      "Guinea",
      "Honduras",
      "Ivory Coast",
      "Kenya",
      "Kiribati",
      "Kosovo",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Liberia",
      "Madagascar",
      "Malawi",
      "Mali",
      "Marshall Islands",
      "Mauritania",
      "Micronesia",
      "Mongolia",
      "Mozambique",
      "Myanmar",
      "Nauru",
      "Nepal",
      "Niger",
      "Nigeria",
      "Niue",
      "Pakistan",
      "Palau",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Republic of Moldova",
      "Rwanda",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "Sao Tome and Principe",
      "Senegal",
      "Sierra Leone",
      "Solomon Islands",
      "Somalia",
      "South Sudan",
      "Sudan",
      "Tajikistan",
      "Timor-Leste",
      "Togo",
      "Tonga",
      "Tuvalu",
      "Uganda",
      "United Republic of Tanzania",
      "Uruguay",
      "Vanuatu",
      "Vietnam",
      "Yemen",
      "Zimbabwe"
    ],
    "Development Partner": [
      "Angola",
      "Australia",
      "Austria",
      "Belgium",
      "Canada",
      "Colombia",
      "Congo",
      "Czech Republic",
      "Denmark",
      "El Salvador",
      "Finland",
      "France",
      "Gabon",
      "Germany",
      "Ireland",
      "Italy",
      "Japan",
      "Luxembourg",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Papua New Guinea",
      "Portugal",
      "Republic of Korea",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "United Kingdom of Great Britain and Northern Ireland",
      "United States of America"
    ]
  },
  "Aggregate": {
    "Region": [
      "Africa",
      "East Asia",
      "Eastern Europe and Central Asia",
      "Latin America and the Caribbean",
      "Pacific",
      "South Asia"
    ],
    "Income Group": [
      "Low income",
      "Lower middle income",
      "Upper middle income"
    ],
    "Country Context": [
      "Least Developed Countries (LDC) ",
      "Landlocked Least Developed Countries (LLDC)",
      "Small Island Developing States (SIDS)"
    ]
  }
};