export let titles = [
  {
    "year": "2014",
    "categories": [
      {
        "id": "5a",
        "label": "5a: How reliable is the disbursement of funding by development partners?",
        "title": "Indicator 5a: How reliable is the disbursement of funding by development partners?",
        "subcategories": [],
        "column": "_2014_5a",
        "prefix": "",
        "suffix": "of development co-operation funding was disbursed within the fiscal year within which it was scheduled.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed within scheduled fiscal year",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 5a: Annual predictability of development co-operation"
      },
      {
        "id": "5b",
        "label": "5b: Are development partners sharing forward-looking information on planned funding?",
        "title": "Indicator 5b: Are development partners sharing forward-looking information on planned funding?",
        "subcategories": [],
        "column": "_2014_5b",
        "prefix": "",
        "suffix": "of development co-operation funding is covered by indicative forward spending plans provided at country level.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding covered by development partners' forward expenditure plans",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 5b: Medium-term predictability of development co-operation"
      },
      {
        "id": "6",
        "label": "6: Do partner countries' legislatures have oversight over development funding?",
        "title": "Indicator 6: Do partner countries' legislatures have oversight over development funding?",
        "subcategories": [],
        "column": "_2014_6",
        "prefix": "",
        "suffix": "of development co-operation funding scheduled for disbursement is included in national budgets subject to parliamentary oversight.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding included in the partner country's budget ",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 6: Development co-operation is on budgets which are subject to parliamentary scrutiny"
      },
      {
        "id": "7",
        "label": "7: Are partner countries conducting inclusive mutual reviews with development partners?",
        "title": "Indicator 7: According to Global Partnership criteria, are partner countries conducting inclusive mutual reviews with development partners?",
        "subcategories": [
          {
            "label": "Is there an aid or partnership policy in place?",
            "column": "_2014_7_1",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 1: An aid or partnership policy <b>is</b> in place.",
            "noText": "Criterion 1: An aid or partnership policy <b>is not</b> in place.",
            "legendText": "Is an aid or partnership policy in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of an aid or partnership policy (Indicator 7)"
          },
          {
            "label": "Have country-level targets for development co-operation been established?",
            "column": "_2014_7_2",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 2: Local targets for development co-operation <b>have</b> been established.",
            "noText": "Criterion 2: Local targets for development co-operation <b>have not been</b> established.",
            "legendText": "Are country-level partnership targets in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of country-level targets for development co-operation (Indicator 7)"
          },
          {
            "label": "Do governments and development partners conduct regular joint assessments towards country-level targets?",
            "column": "_2014_7_3",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 3: Government and development partners conduct regular joint assessment towards targets.",
            "noText": "Criterion 3: Government and development partners do not conduct regular joint assessment towards targets.",
            "legendText": "Are there regular joint assessments among partners?",
            "type": "text",
            "precision": "0",
            "title": "Existence of joint assessments towards country-level targets (Indicator 7)"
          },
          {
            "label": "Are non-executive stakeholders involved in joint assessments?",
            "column": "_2014_7_4",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 4: Non-executive stakeholders <b>are</b> involved in joint assessments.",
            "noText": "Criterion 4: Non-executive stakeholders <b>are not</b> involved in joint assessments.",
            "legendText": "Are non-executive stakeholders included in joint assessments?",
            "type": "text",
            "precision": "0",
            "title": "Involvement of non-executive stakeholders in joint assessments"
          },
          {
            "label": "Are joint assessments between government and development partners made public?",
            "column": "_2014_7_5",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 5: Results of joint assessments <b>are</b> made public.",
            "noText": "Criterion 5: Results or joint assessments <b>are not</b> made public.",
            "legendText": "Are joint assessments made public?",
            "type": "text",
            "precision": "0",
            "title": "Publicly-available joint assessments between development partners (Indicator 7)"
          }
        ],
        "column": "_2014_7",
        "prefix": "",
        "suffix": "",
        "yesText": "According to Global Partnership criteria, there <b>is</b> an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria). ",
        "noText": "According to Global Partnership criteria, there <b>is not</b> an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria). ",
        "legendText": "Is a process for inclusive reviews in place?",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 7: Mutual accountability among development partners is strengthened through inclusive reviews"
      },
      {
        "id": "8",
        "label": "8: Do partner countries track public allocations for gender equality?",
        "title": "Indicator 8: According to Global Partnership criteria, do partner countries track public allocations for gender equality?",
        "subcategories": [
          {
            "label": "Do partner countries meet the Global Partnership's criteria for tracking public allocations for gender equality and women's empowerment?",
            "column": "_2014_8",
            "prefix": "",
            "suffix": "",
            "yesText": "According to Global Partnership criteria, there <b>is</b> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
            "noText": "According to Global Partnership criteria, there <b>is not</b> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 <b>and</b> Criteria 4).",
            "legendText": "Do partner countries track public allocations for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Indicator 8: According to Global Partnership criteria, do partner countries track public allocations for gender equality?"
          },
          {
            "label": "Does a government statement establishing a tracking system for gender equality exist?",
            "column": "_2014_8_1",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 1: There <b>is</b> an official government statement defining the system for tracking allocations for gender equality and women's empowerment.",
            "noText": "Criterion 1: There <b>is not</b> an official government statement defining the system for tracking allocations for gender equality and women's empowerment.",
            "legendText": "Is there a government statement on a tracking system for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Existence of a government statement establishing a tracking system for gender equality (Indicator 8)"
          },
          {
            "label": "Are public allocations for gender equality systematically tracked?",
            "column": "_2014_8_2",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 2: Gender allocations <b>are</b> systematically tracked.",
            "noText": "Criterion 2: Gender allocations <b>are not</b> systematically tracked.",
            "legendText": "Is there a government system for tracking allocations for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Systematic tracking of public allocations for gender equality (Indicator 8)"
          },
          {
            "label": "Does a central government unit provide leadership and oversight of a tracking system for gender equality allocations?",
            "column": "_2014_8_3",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 3: There <b>is</b> a central government unit in charge of oversight for tracking allocations for gender equality and women's empowerment.",
            "noText": "Criterion 3: There <b>is not</b> a central government unit in charge of oversight for tracking allocations for gender equality and women's empowerment.",
            "legendText": "Is there a central government unit providing leadership and oversight for gender allocations?",
            "type": "text",
            "precision": "0",
            "title": "Existence of a central government unit to provide leadership and oversight (Indicator 8)"
          },
          {
            "label": "Is gender-equality-focused budget information publicly available?",
            "column": "_2014_8_4",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 4: Gender-related budget information <b>is</b> publicly available.",
            "noText": "Criterion 4: Gender-related budget information <b>is not</b> publicly available.",
            "legendText": "Are budget allocations for gender equality publicly available?",
            "type": "text",
            "precision": "0",
            "title": "Public availability of gender-equality-focused budget information (Indicator 8)"
          }
        ],
        "column": "_2014_8",
        "prefix": "",
        "suffix": "",
        "yesText": "According to Global Partnership criteria, there <b>is</b> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
        "noText": "According to Global Partnership criteria, there <b>is not</b> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 <b>and</b> Criteria 4).",
        "legendText": "Do partner countries track public allocations for gender equality?",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 8: Governments have systems in place to track allocations for gender equality and women’s empowerment"
      },
      {
        "id": "9a",
        "label": "9a: How robust are countries' national public financial management and procurement systems?",
        "title": "Indicator 9a: How robust are countries' national public financial management and procurement systems?",
        "subcategories": [],
        "column": "_2014_9a",
        "prefix": "Country Policy and Institutional Assessment (CPIA) score:",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "How reliable is the budget and financial management system (6 is ideal)?",
        "type": "number",
        "precision": "1",
        "footer": "Indicator 9a: Quality of partner countries’ public financial management systems"
      },
      {
        "id": "9b",
        "label": "9b: Are development partners using country systems?",
        "title": "Indicator 9b: Are development partners using country systems?",
        "subcategories": [],
        "column": "_2014_9b",
        "prefix": "",
        "suffix": "of development co-operation funding disbursed for the government sector used its own public financial management and procurement systems.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed using partner countries' own systems",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 9b: Use of partner countries’ own public financial management and procurement systems to deliver development co-operation"
      },
      {
        "id": "10",
        "label": "10: Is aid untied?",
        "title": "Indicator 10: Is aid untied?",
        "subcategories": [],
        "column": "_2014_10",
        "prefix": "",
        "suffix": "of development co-operation is untied.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of aid that is fully untied",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 10. Aid is untied"
      }
    ]
  },
  {
    "year": "2016",
    "categories": [
      {
        "id": "1a",
        "label": "1a: Do development partners use countries' own results frameworks and evaluation processes? ",
        "title": "Indicator 1a: Do development partners use partner countries' own results frameworks and evaluation processes?",
        "subcategories": [
          {
            "label": "% of new development interventions that draw their objectives from country-led results frameworks",
            "column": "_2016_1_1",
            "prefix": "",
            "suffix": "of new development interventions draw their objectives from country-led results frameworks.",
            "yesText": "",
            "noText": "",
            "legendText": "% of interventions ",
            "type": "percent",
            "precision": "1",
            "title": "% of new development interventions that draw their objectives from country-led results frameworks (Indicator 1a)"
          },
          {
            "label": "% of results indicators drawn from country-led results frameworks",
            "column": "_2016_1_2",
            "prefix": "",
            "suffix": "of results indicators are drawn from country / government-led results frameworks.",
            "yesText": "",
            "noText": "",
            "legendText": "% of results indicators ",
            "type": "percent",
            "precision": "1",
            "title": "% of results indicators drawn from country-led results frameworks (Indicator 1a)"
          },
          {
            "label": "% of results indicators monitored using the partner country's own sources",
            "column": "_2016_1_3",
            "prefix": "",
            "suffix": "of results indicators are monitored using the partner country’s own sources and monitoring systems.",
            "yesText": "",
            "noText": "",
            "legendText": "% of results indicators ",
            "type": "percent",
            "precision": "1",
            "title": "% of results indicators monitored using the partner country's own sources (Indicator 1a)"
          },
          {
            "label": "% of new interventions that plan a final evaluation with partner country involvement",
            "column": "_2016_1_4",
            "prefix": "",
            "suffix": "of new interventions plan a final evaluation with partner country involvement.",
            "yesText": "",
            "noText": "",
            "legendText": "% of new interventions ",
            "type": "percent",
            "precision": "1",
            "title": "% of new interventions that plan a final evaluation with partner country involvement (Indicator 1a)"
          }
        ],
        "column": "_2016_1",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 1a: Development partners' use of country-led results frameworks "
      },
      {
        "id": "2",
        "label": "2: Are CSOs engaged in the development effectiveness process?",
        "title": "Indicator 2: Are CSOs engaged in the development effectiveness process?",
        "subcategories": [
          {
            "label": "Do governments support multi-stakeholder dialogue on national development policies?",
            "column": "_2016_2_1",
            "prefix": "Module 1:",
            "suffix": "out of 3 criteria have been met for availability of spaces for multi-stakeholder dialogue on national development policies. ",
            "yesText": "",
            "noText": "",
            "legendText": "Criteria met for 'availability of space for multi-stakeholder dialogue' (3 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Do governments support multi-stakeholder dialogue on national development policies? (Indicator 2)"
          },
          {
            "label": "Do CSOs adhere to the development effectiveness principles?",
            "column": "_2016_2_2",
            "prefix": "Module 2:",
            "suffix": "out of 5 criteria have been met for CSO adherence to the development effectiveness principles of co-ordination, accountability and transparency. ",
            "yesText": "",
            "noText": "",
            "legendText": "Criteria met for 'CSOs' own transparency and accountability' (4 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Do CSOs adhere to the development effectiveness principles? (Indicator 2)"
          },
          {
            "label": "Do official development partners co-operate with CSOs?",
            "column": "_2016_2_3",
            "prefix": "Module 3:",
            "suffix": "out of 4 criteria have been met for official development co-operation with CSOs.",
            "yesText": "",
            "noText": "",
            "legendText": "Criteria met for 'official development co-operation with CSOs' (4 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Do official development partners co-operate with CSOs? (Indicator 2)"
          },
          {
            "label": "How enabling is the legal and regulatory environment for CSOs?",
            "column": "_2016_2_4",
            "prefix": "Module 4:",
            "suffix": "out of 4 criteria have been met for having enabling legal and regulatory environment for CSO contribution to development.",
            "yesText": "",
            "noText": "",
            "legendText": "Criteria met for an 'enabling regulatory environment for CSOs' (4 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Is there an enabling legal and regulatory environment for CSOs' engagement in development? (Indicator 2)"
          }
        ],
        "column": "_2016_2",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 2: Assessment of an enabling environment for civil society participation in development co-operation "
      },
      {
        "id": "3",
        "label": "3: What is the quality of public-private dialogue?",
        "title": "Indicator 3: What is the quality of public-private dialogue?",
        "subcategories": [
          {
            "label": "Is the private sector willing to engage in public-private dialogue?",
            "column": "_2016_3_1",
            "prefix": "Private sector willingness to engage in public-private dialogue scored",
            "suffix": "on a scale of 0-10, with 10 indicating strongest performance and 0 indicating the weakest. ",
            "yesText": "",
            "noText": "",
            "legendText": "Willingness of the private sector to engage in public-private dialogue (10 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Is the private sector willing to engage in public-private dialogue? (Indicator 3)"
          },
          {
            "label": "Is the government willing to engage in public-private dialogue?",
            "column": "_2016_3_2",
            "prefix": "Government willingness to engage in public-private dialogue scored",
            "suffix": "on a scale of 0-10, with 10 indicating strongest performance and 0 indicating the weakest. ",
            "yesText": "",
            "noText": "",
            "legendText": "Willingness of the government to engage in public-private dialogue (10 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Is the government willing to engage in public-private dialogue? (Indicator 3)"
          },
          {
            "label": "Is there a potential champion who can facilitate public-private dialogue?",
            "column": "_2016_3_3",
            "prefix": "Existence of a potential champion to facilitate public-private dialogue scored",
            "suffix": "on a scale of 0-10, with 10 indicating strongest performance and 0 indicating the weakest. ",
            "yesText": "",
            "noText": "",
            "legendText": "Existence of champions to facilitate public-private dialogue (10 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Is there a potential champion who can facilitate public-private dialogue? (Indicator 3)"
          },
          {
            "label": "Are instruments available to support public-private dialogue?",
            "column": "_2016_3_4",
            "prefix": "Availability of instruments to facilitate public-private dialogue scored",
            "suffix": "on a scale of 0-10, with 10 indicating strongest performance and 0 indicating the weakest. ",
            "yesText": "",
            "noText": "",
            "legendText": "Instruments available to facilitate public-private dialogue (10 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Are instruments available to support public-private dialogue? (Indicator 3)"
          }
        ],
        "column": "_2016_3",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 3: Quality of public-private dialogue "
      },
      {
        "id": "4",
        "label": "4: Are development partners making high-quality information on development funding publicly accessible?",
        "title": "Indicator 4: Are development partners making high-quality information on development funding publicly accessible?",
        "subcategories": [
          {
            "label": "Assessment of the OECD CRS (backward-looking data for accountability purposes)",
            "column": "_2016_4_1",
            "prefix": "Overall transparency assessment of the OECD Creditor Reporting System providing backward-looking data for accountability purposes:",
            "suffix": "",
            "yesText": "",
            "noText": "",
            "legendText": "How robust are donors' activity-level records of funding?",
            "type": "text",
            "precision": "0",
            "title": "Assessment by the OECD Creditor Reporting System (CRS) - Indicator 4"
          },
          {
            "label": "Assessment of the OECD FSS (data for forecasting purposes)",
            "column": "_2016_4_2",
            "prefix": "Overall transparency assessment of the OECD Forward Spending Survey for forecasting purposes:",
            "suffix": "",
            "yesText": "",
            "noText": "",
            "legendText": "How strong are donors' forward spending plans?",
            "type": "text",
            "precision": "0",
            "title": "Assessment by the OECD Forward Spending Survey (FSS) - Indicator 4 "
          },
          {
            "label": "Assessment of the IATI (data for aid management and planning purposes)",
            "column": "_2016_4_3",
            "prefix": "Overall transparency assessment of the International Aid Transparency Initiative (IATI) for aid management and planning purposes:",
            "suffix": "",
            "yesText": "",
            "noText": "",
            "legendText": "Are donors' reporting information in a timely, comprehensive and forward looking manner?",
            "type": "text",
            "precision": "0",
            "title": "Assessment by the International Aid Transparency Initiative (IATI) - Indicator 4"
          }
        ],
        "column": "_2016_4",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 4: Transparent information on development co-operation is publicly available"
      },
      {
        "id": "5a",
        "label": "5a: How reliable is the disbursement of funding by development partners?",
        "title": "Indicator 5a: How reliable is the disbursement of funding by development partners?",
        "subcategories": [],
        "column": "_2016_5a",
        "prefix": "",
        "suffix": "of development co-operation funding was disbursed within the fiscal year within which it was scheduled.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed within scheduled fiscal year",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 5a: Annual predictability of development co-operation"
      },
      {
        "id": "5b",
        "label": "5b: Are development partners sharing forward-looking information on planned funding with partner countries?",
        "title": "Indicator 5b: Are development partners sharing forward-looking information on planned funding?",
        "subcategories": [],
        "column": "_2016_5b",
        "prefix": "",
        "suffix": "of development co-operation funding is covered by indicative forward spending plans provided at the country level.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding covered by development partners' forward expenditure plans",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 5b: Medium-term predictability of development co-operation"
      },
      {
        "id": "6",
        "label": "6: Do partner countries' legislatures have oversight over development funding?",
        "title": "Indicator 6: Do partner countries' legislatures have oversight over development funding?",
        "subcategories": [],
        "column": "_2016_6",
        "prefix": "",
        "suffix": "of development co-operation funding scheduled for disbursement is included in national budgets subject to parliamentary oversight.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding included in the partner country's budget ",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 6: Development co-operation is on budgets which are subject to parliamentary scrutiny"
      },
      {
        "id": "7",
        "label": "7: Are partner countries conducting inclusive mutual reviews with development partners?",
        "title": "Indicator 7: According to Global Partnership criteria, are partner countries conducting inclusive mutual reviews with development partners?",
        "subcategories": [
          {
            "label": "Is there an aid or partnership policy in place?",
            "column": "_2016_7_1",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 1: An aid or partnership policy <b>is</b> in place.",
            "noText": "Criterion 1: An aid or partnership policy <b>is not</b> in place.",
            "legendText": "Is an aid or partnership policy in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of an aid or partnership policy (Indicator 7)"
          },
          {
            "label": "Have country-level targets for development co-operation been established?",
            "column": "_2016_7_2",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 2: Local targets for development co-operation <b>have</b> been established.",
            "noText": "Criterion 2: Local targets for development co-operation <b>have not been</b> established.",
            "legendText": "Are country-level partnership targets in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of country-level targets for development co-operation (Indicator 7)"
          },
          {
            "label": "Do governments and development partners conduct regular joint assessments towards country-level targets?",
            "column": "_2016_7_3",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 3: Government and development partners conduct regular joint assessment towards targets.",
            "noText": "Criterion 3: Government and development partners do not conduct regular joint assessment towards targets.",
            "legendText": "Are there regular joint assessments among partners?",
            "type": "text",
            "precision": "0",
            "title": "Existence of joint assessments towards country-level targets (Indicator 7)"
          },
          {
            "label": "Are non-executive stakeholders involved in joint assessments?",
            "column": "_2016_7_4",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 4: Non-executive stakeholders <b>are</b> involved in joint assessments.",
            "noText": "Criterion 4: Non-executive stakeholders <b>are not</b> involved in joint assessments.",
            "legendText": "Are non-executive stakeholders included in joint assessments?",
            "type": "text",
            "precision": "0",
            "title": "Involvement of non-executive stakeholders in joint assessments"
          },
          {
            "label": "Are joint assessments between government and development partners made public?",
            "column": "_2016_7_5",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 5: Results of joint assessments <b>are</b> made public.",
            "noText": "Criterion 5: Results of joint assessments <b>are not</b> made public.",
            "legendText": "Are joint assessments made public?",
            "type": "text",
            "precision": "0",
            "title": "Publicly-available joint assessments between development partners (Indicator 7)"
          }
        ],
        "column": "_2016_7",
        "prefix": "",
        "suffix": "",
        "yesText": "According to Global Partnership criteria, there <b>is</b> an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria).",
        "noText": "According to Global Partnership criteria, there <b>is not</b> an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria). ",
        "legendText": "Is a process for inclusive reviews in place?",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 7: Mutual accountability among development partners is strengthened through inclusive reviews"
      },
      {
        "id": "8",
        "label": "8: Do partner countries track public allocations for gender equality?",
        "title": "Indicator 8: According to Global Partnership criteria, do partner countries track public allocations for gender equality?",
        "subcategories": [
          {
            "label": "Do partner countries meet the Global Partnership's criteria for tracking public allocations for gender equality and women's empowerment?",
            "column": "_2016_8",
            "prefix": "",
            "suffix": "",
            "yesText": "According to Global Partnership criteria, there <b>is</b> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
            "noText": "According to Global Partnership criteria, there <b>is not</b> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 <b>and</b> Criteria 4).",
            "legendText": "Do partner countries track public allocations for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Indicator 8: According to Global Partnership criteria, do partner countries track public allocations for gender equality?"
          },
          {
            "label": "Does a government statement establishing a tracking system for gender equality exist?",
            "column": "_2016_8_1",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 1: There <b>is</b> an official government statement defining the system for tracking allocations for gender equality and women's empowerment.",
            "noText": "Criterion 1: There <b>is not</b> an official government statement defining the system for tracking allocations for gender equality and women's empowerment.",
            "legendText": "Is there a government statement on a tracking system for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Existence of a government statement establishing a tracking system for gender equality (Indicator 8)"
          },
          {
            "label": "Are public allocations for gender equality systematically tracked?",
            "column": "_2016_8_2",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 2: Gender allocations <b>are</b> systematically tracked.",
            "noText": "Criterion 2: Gender allocations <b>are not</b> systematically tracked.",
            "legendText": "Is there a government system for tracking allocations for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Systematic tracking of public allocations for gender equality (Indicator 8)"
          },
          {
            "label": "Does a central government unit provide leadership and oversight of a tracking system for gender equality allocations?",
            "column": "_2016_8_3",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 3: There <b>is</b> a central government unit in charge of oversight for tracking allocations for gender equality and women's empowerment.",
            "noText": "Criterion 3: There <b>is not</b> a central government unit in charge of oversight for tracking allocations for gender equality and women's empowerment.",
            "legendText": "Is there a central government unit providing leadership and oversight for gender allocations?",
            "type": "text",
            "precision": "0",
            "title": "Existence of a central government unit to provide leadership and oversight (Indicator 8)"
          },
          {
            "label": "Is gender-equality-focused budget information publicly available?",
            "column": "_2016_8_4",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 4: Gender-related budget information <b>is</b> publicly available.",
            "noText": "Criterion 4: Gender-related budget information <b>is not</b> publicly available.",
            "legendText": "Are budget allocations for gender equality publicly available?",
            "type": "text",
            "precision": "0",
            "title": "Public availability of gender-equality-focused budget information (Indicator 8)"
          }
        ],
        "column": "_2016_8",
        "prefix": "",
        "suffix": "",
        "yesText": "According to Global Partnership criteria, there <b>is</b> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
        "noText": "According to Global Partnership criteria, there <b>is not</b> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 <b>and</b> Criteria 4).",
        "legendText": "Do partner countries track public allocations for gender equality?",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 8: Governments have systems in place to track allocations for gender equality and women’s empowerment"
      },
      {
        "id": "9a",
        "label": "9a: How robust are countries' national public financial management and procurement systems?",
        "title": "9a: How robust are countries' national public financial management and procurement systems?",
        "subcategories": [],
        "column": "_2016_9a",
        "prefix": "Country Policy and Institutional Assessment (CPIA) score:",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "How reliable is the budget and financial management system (6 is ideal)?",
        "type": "number",
        "precision": "1",
        "footer": "Indicator 9a: Quality of partner countries’ public financial management systems"
      },
      {
        "id": "9b",
        "label": "9b: Are development partners using country systems?",
        "title": "9b: Are development partners using country systems?",
        "subcategories": [],
        "column": "_2016_9b",
        "prefix": "",
        "suffix": "of development co-operation funding disbursed for the government sector used their own public financial management and procurement systems.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed using the countries' own systems",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 9b: Use of partner countries’ own public financial management and procurement systems to deliver development co-operation"
      },
      {
        "id": "10",
        "label": "10: Is aid untied?",
        "title": "10: Is aid untied?",
        "subcategories": [],
        "column": "_2016_10",
        "prefix": "",
        "suffix": "of development co-operation has been untied.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of aid that is fully untied",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 10. Aid is untied"
      }
    ]
  }
];