export let titles = [
  {
    "year": "2010",
    "categories": [
      {
        "id": "5a",
        "label": "5a: How reliable is the disbursement of funding by development partners?",
        "title": "Indicator 5a: How reliable is the disbursement of funding by development partners? ",
        "subcategories": [],
        "column": "_2010_5a",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed within scheduled fiscal year",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 5a: Annual predictability of development co-operation",
        "comparison": "<font color=”black”> Indicator 5a: </font> Annual predictability of development co-operation",
        "partcntry": "_2010_5a_partcntry",
        "devpart": "_2010_5a_devpart"
      },
      {
        "id": "6",
        "label": "6: Do partner countries' legislatures have oversight over development funding?",
        "title": "Indicator 6: Do partner countries' legislatures have oversight over development funding?",
        "subcategories": [],
        "column": "_2010_6",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding included in the partner country's budget",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 6: Development co-operation is on budgets which are subject to parliamentary scrutiny",
        "comparison": "<font color=”black”> Indicator 6: </font> Development co-operation is on budgets which are subject to parliamentary scrutiny",
        "partcntry": "_2010_6_partcntry",
        "devpart": "_2010_6_devpart"
      },
      {
        "id": "7",
        "label": "7: Are partner countries conducting inclusive mutual reviews with development partners?",
        "title": "Indicator 7: According to Global Partnership criteria, are partner countries conducting inclusive mutual reviews with development partners? ",
        "subcategories": [
          {
            "label": "Are partner countries conducting inclusive mutual reviews with development partners?",
            "column": "_2010_7",
            "prefix": "",
            "suffix": "",
            "yesText": "According to Global Partnership criteria, there <font color='black'>  is </font> an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria).",
            "noText": "",
            "legendText": "Is a process for inclusive reviews in place?",
            "type": "text",
            "precision": "0",
            "title": "Indicator 7: According to Global Partnership criteria, are partner countries conducting inclusive mutual reviews with development partners? ",
            "comparison": "<font color=”black”> Indicator 7: </font> Mutual accountability among development partners is strengthened through inclusive reviews",
            "partcntry": "_2010_7",
            "devpart": ""
          },
          {
            "label": "Is there an aid or partnership policy in place?",
            "column": "_2010_7_1",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 1: An aid or partnership policy  <font color='black'> is </font> in place.",
            "noText": "",
            "legendText": "Is an aid or partnership policy in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of an aid or partnership policy (Indicator 7)",
            "comparison": "Existence of an aid or partnership policy",
            "partcntry": "_2010_7_1",
            "devpart": ""
          },
          {
            "label": "Have country-level targets for development co-operation been established?",
            "column": "_2010_7_2",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 2: Local targets for development co-operation <font color='black'> have </font> been established.",
            "noText": "",
            "legendText": "Are country-level partnership targets in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of country-level targets for development co-operation (Indicator 7) ",
            "comparison": "Existence of country-level targets for development co-operation",
            "partcntry": "_2010_7_2",
            "devpart": ""
          },
          {
            "label": "Do governments and development partners conduct regular joint assessments towards country-level targets?",
            "column": "_2010_7_3",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 3: Government and development partners conduct regular joint assessment towards targets.",
            "noText": "",
            "legendText": "Are there regular joint assessments among partners?",
            "type": "text",
            "precision": "0",
            "title": "Existence of joint assessments towards country-level targets (Indicator 7) ",
            "comparison": "Existence of regular joint assessments between government and development partners",
            "partcntry": "_2010_7_3",
            "devpart": ""
          },
          {
            "label": "Are non-executive stakeholders involved in joint assessments?",
            "column": "_2010_7_4",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 4: Non-executive stakeholders <font color='black'> are </font> involved in joint assessments.",
            "noText": "",
            "legendText": "Are non-executive stakeholders included in joint assessments?",
            "type": "text",
            "precision": "0",
            "title": "Involvement of non-executive stakeholders in joint assessments ",
            "comparison": "Involvement of non-executive stakeholders in joint assessments",
            "partcntry": "_2010_7_4",
            "devpart": ""
          },
          {
            "label": "Are joint assessments between government and development partners made public?",
            "column": "_2010_7_5",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 5: Results of joint assessments <font color='black'> are </font> made public.",
            "noText": "",
            "legendText": "Are joint assessments made public?",
            "type": "text",
            "precision": "0",
            "title": "Publicly-available joint assessments between development partners (Indicator 7) ",
            "comparison": "Existence of publicly-available information on joint assessments",
            "partcntry": "_2010_7_5",
            "devpart": ""
          }
        ],
        "column": "_2010_7",
        "prefix": "",
        "suffix": "",
        "yesText": "According to Global Partnership criteria, there <font color='black'>  is </font> an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria).",
        "noText": "",
        "legendText": "Is a process for inclusive reviews in place?",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 7: Mutual accountability among development partners is strengthened through inclusive reviews",
        "comparison": "<font color=”black”> Indicator 7: </font> Mutual accountability among development partners is strengthened through inclusive reviews",
        "partcntry": "_2010_7",
        "devpart": ""
      },
      {
        "id": "9a",
        "label": "9a: How robust are countries' national public financial management and procurement systems?",
        "title": "Indicator 9a: How robust are countries' national public financial management and procurement systems?",
        "subcategories": [],
        "column": "_2010_9a",
        "prefix": "Country Policy and Institutional Assessment (CPIA) score:",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "How reliable is the budget and financial management system (6 is ideal)?",
        "type": "number",
        "precision": "1",
        "footer": "Indicator 9a: Quality of partner countries’ public financial management systems",
        "comparison": "<font color=”black”> Indicator 9a: </font> Quality of countries’ public financial management systems",
        "partcntry": "_2010_9a",
        "devpart": ""
      },
      {
        "id": "9b",
        "label": "9b: Are development partners using country systems?",
        "title": "Indicator 9b: Are development partners using country systems? ",
        "subcategories": [],
        "column": "_2010_9b",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed using partner countries' own systems",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 9b: Use of partner countries’ own public financial management and procurement systems to deliver development co-operation",
        "comparison": "<font color=”black”> Indicator 9b: </font> Use of partner countries’ public financial management and procurement systems to deliver development co-operation",
        "partcntry": "_2010_9b",
        "devpart": "_2010_9b"
      },
      {
        "id": "10",
        "label": "10: Is aid untied?",
        "title": "Indicator 10: Is aid untied? ",
        "subcategories": [],
        "column": "_2010_10",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "Share of aid that is fully untied",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 10. Aid is untied",
        "comparison": "<font color=”black”> Indicator 10: </font> Aid is untied",
        "partcntry": "_2010_10_partcntry",
        "devpart": "_2010_10_devpart"
      }
    ]
  },
  {
    "year": "2014",
    "categories": [
      {
        "id": "5a",
        "label": "5a: How reliable is the disbursement of funding by development partners?",
        "title": "Indicator 5a: How reliable is the disbursement of funding by development partners?",
        "subcategories": [],
        "column": "_2014_5a",
        "prefix": "",
        "suffix": "of development funding was disbursed within the scheduled fiscal year. ",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed within scheduled fiscal year",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 5a: Annual predictability of development co-operation",
        "comparison": "<font color=\"black\">Indicator 5a:</font> Annual predictability of development co-operation",
        "partcntry": "_2014_5a_partcntry",
        "devpart": "_2014_5a_devpart"
      },
      {
        "id": "5b",
        "label": "5b: Are development partners sharing forward-looking information on planned funding?",
        "title": "Indicator 5b: Are development partners sharing forward-looking information on planned funding?",
        "subcategories": [],
        "column": "_2014_5b",
        "prefix": "",
        "suffix": "of development funding was covered by forward spending plans provided by development partners.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding covered by development partners' forward expenditure plans",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 5b: Medium-term predictability of development co-operation",
        "comparison": "<font color=\"black\">Indicator 5b:</font> Medium-term predictability of development co-operation",
        "partcntry": "_2014_5b_partcntry",
        "devpart": "_2014_5b_devpart"
      },
      {
        "id": "6",
        "label": "6: Do partner countries' legislatures have oversight over development funding?",
        "title": "Indicator 6: Do partner countries' legislatures have oversight over development funding?",
        "subcategories": [],
        "column": "_2014_6",
        "prefix": "",
        "suffix": "of development funding scheduled for disbursement was included in national budgets overseen by the legislature. ",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding included in the partner country's budget ",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 6: Development co-operation is on budgets which are subject to parliamentary scrutiny",
        "comparison": "<font color=\"black\">Indicator 6:</font> Development co-operation is on budgets which are subject to parliamentary scrutiny",
        "partcntry": "_2014_6_partcntry",
        "devpart": "_2014_6_devpart"
      },
      {
        "id": "7",
        "label": "7: Are partner countries conducting inclusive mutual reviews with development partners?",
        "title": "Indicator 7: According to Global Partnership criteria, are partner countries conducting inclusive mutual reviews with development partners?",
        "subcategories": [
          {
            "label": "Is there an aid or partnership policy in place?",
            "column": "_2014_7_1",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 1: An aid or partnership policy <font color='black'> is </font> in place.",
            "noText": "Criterion 1: An aid or partnership policy <font color='black'> is not </font> in place.",
            "legendText": "Is an aid or partnership policy in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of an aid or partnership policy (Indicator 7)",
            "comparison": "<font color=\"black\">Indicator 7:</font> Existence of an aid or partnership policy",
            "partcntry": "_2014_7_1",
            "devpart": ""
          },
          {
            "label": "Have country-level targets for development co-operation been established?",
            "column": "_2014_7_2",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 2: Local targets for development co-operation <font color='black'> have </font> been established.",
            "noText": "Criterion 2: Local targets for development co-operation <font color='black'> have not </font> been established.",
            "legendText": "Are country-level partnership targets in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of country-level targets for development co-operation (Indicator 7)",
            "comparison": "<font color=\"black\">Indicator 7:</font> Existence of country-level targets for development co-operation",
            "partcntry": "_2014_7_2",
            "devpart": ""
          },
          {
            "label": "Do governments and development partners conduct regular joint assessments towards country-level targets?",
            "column": "_2014_7_3",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 3: Government and development partners conduct regular joint assessment towards targets.",
            "noText": "Criterion 3: Government and development partners <font color='black'> do not </font> conduct regular joint assessment towards targets.",
            "legendText": "Are there regular joint assessments among partners?",
            "type": "text",
            "precision": "0",
            "title": "Existence of joint assessments towards country-level targets (Indicator 7)",
            "comparison": "<font color=\"black\">Indicator 7:</font> Existence of regular joint assessments between government and development partners",
            "partcntry": "_2014_7_3",
            "devpart": ""
          },
          {
            "label": "Are non-executive stakeholders involved in joint assessments?",
            "column": "_2014_7_4",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 4: Non-executive stakeholders <font color='black'> are </font> involved in joint assessments.",
            "noText": "Criterion 4: Non-executive stakeholders <font color='black'> are not </font> involved in joint assessments.",
            "legendText": "Are non-executive stakeholders included in joint assessments?",
            "type": "text",
            "precision": "0",
            "title": "Involvement of non-executive stakeholders in joint assessments",
            "comparison": "<font color=\"black\">Indicator 7:</font> Involvement of non-executive stakeholders in joint assessments",
            "partcntry": "_2014_7_4",
            "devpart": ""
          },
          {
            "label": "Are joint assessments between government and development partners made public?",
            "column": "_2014_7_5",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 5: Results of joint assessments <font color='black'> are </font> made public.",
            "noText": "Criterion 5: Results of joint assessments <font color='black'> are not </font> made public.",
            "legendText": "Are joint assessments made public?",
            "type": "text",
            "precision": "0",
            "title": "Publicly-available joint assessments between development partners (Indicator 7)",
            "comparison": "<font color=\"black\">Indicator 7:</font> Existence of publicly-available information on joint assessments",
            "partcntry": "_2014_7_5",
            "devpart": ""
          }
        ],
        "column": "_2014_7",
        "prefix": "",
        "suffix": "",
        "yesText": "According to Global Partnership criteria, there <font color='black'> is </font> an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria). ",
        "noText": "According to Global Partnership criteria, there <font color='black'> is not </font> an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria). ",
        "legendText": "Is a process for inclusive reviews in place?",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 7: Mutual accountability among development partners is strengthened through inclusive reviews",
        "comparison": "<font color=\"black\">Indicator 7:</font> Mutual accountability among development partners is strengthened through inclusive reviews",
        "partcntry": "_2014_7",
        "devpart": ""
      },
      {
        "id": "8",
        "label": "8: Do partner countries track public allocations for gender equality?",
        "title": "Indicator 8: According to Global Partnership criteria, do partner countries track public allocations for gender equality?",
        "subcategories": [
          {
            "label": "Do partner countries meet the Global Partnership's criteria for tracking public allocations for gender equality and women's empowerment?",
            "column": "_2014_8",
            "prefix": "",
            "suffix": "",
            "yesText": "According to Global Partnership criteria, there <font color='black'> is </font> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
            "noText": "According to Global Partnership criteria, there <font color='black'> is not </font> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
            "legendText": "Do partner countries track public allocations for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Indicator 8: According to Global Partnership criteria, do partner countries track public allocations for gender equality?",
            "comparison": "<font color=\"black\">Indicator 8:</font> Do countries meet the Global Partnership criteria for tracking public allocations for gender equality and women’s empowerment, and making this information publicly available?",
            "partcntry": "_2014_8",
            "devpart": ""
          },
          {
            "label": "Does a government statement establishing a tracking system for gender equality exist?",
            "column": "_2014_8_1",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 1: There <font color='black'> is </font> an official government statement defining the system for tracking allocations for gender equality and women's empowerment.",
            "noText": "Criterion 1: There <font color='black'> is not </font> an official government statement defining the system for tracking allocations for gender equality and women's empowerment.",
            "legendText": "Is there a government statement on a tracking system for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Existence of a government statement establishing a tracking system for gender equality (Indicator 8)",
            "comparison": "<font color=\"black\">Indicator 8:</font> Existence of a government statement establishing a tracking system for gender equality and women's empowerment",
            "partcntry": "_2014_8_1",
            "devpart": ""
          },
          {
            "label": "Are public allocations for gender equality systematically tracked?",
            "column": "_2014_8_2",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 2: Gender allocations <font color='black'> are </font> systematically tracked.",
            "noText": "Criterion 2: Gender allocations <font color='black'> are not </font> systematically tracked.",
            "legendText": "Is there a government system for tracking allocations for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Systematic tracking of public allocations for gender equality (Indicator 8)",
            "comparison": "<font color=\"black\">Indicator 8:</font> Governments systematically track public allocations for gender equality and women’s empowerment",
            "partcntry": "_2014_8_2",
            "devpart": ""
          },
          {
            "label": "Does a central government unit provide leadership and oversight of a tracking system for gender equality allocations?",
            "column": "_2014_8_3",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 3: There <font color='black'> is </font> a central government unit in charge of oversight for tracking allocations for gender equality and women's empowerment.",
            "noText": "Criterion 3: There <font color='black'> is not </font> a central government unit in charge of oversight for tracking allocations for gender equality and women's empowerment.",
            "legendText": "Is there a central government unit providing leadership and oversight for gender allocations?",
            "type": "text",
            "precision": "0",
            "title": "Existence of a central government unit to provide leadership and oversight (Indicator 8)",
            "comparison": "<font color=\"black\">Indicator 8:</font> A central government unit provides leadership and oversight of a tracking system for gender equality allocations",
            "partcntry": "_2014_8_3",
            "devpart": ""
          },
          {
            "label": "Is gender-equality-focused budget information publicly available?",
            "column": "_2014_8_4",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 4: Gender-related budget information <font color='black'> is </font> publicly available.",
            "noText": "Criterion 4: Gender-related budget information <font color='black'> is not </font> publicly available.",
            "legendText": "Are budget allocations for gender equality publicly available?",
            "type": "text",
            "precision": "0",
            "title": "Public availability of gender-equality-focused budget information (Indicator 8)",
            "comparison": "<font color=\"black\">Indicator 8:</font> Existence of pubicly-available information on budget allocations for gender equality",
            "partcntry": "_2014_8_4",
            "devpart": ""
          }
        ],
        "column": "_2014_8",
        "prefix": "",
        "suffix": "",
        "yesText": "According to Global Partnership criteria, there <font color='black'> is </font> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
        "noText": "According to Global Partnership criteria, there <font color='black'> is not </font> a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
        "legendText": "Do partner countries track public allocations for gender equality?",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 8: Governments have systems in place to track allocations for gender equality and women’s empowerment",
        "comparison": "<font color=\"black\">Indicator 8:</font> Do countries meet the Global Partnership criteria for tracking public allocations for gender equality and women’s empowerment, and making this information publicly available?",
        "partcntry": "_2014_8",
        "devpart": ""
      },
      {
        "id": "9a",
        "label": "9a: How robust are countries' national public financial management and procurement systems?",
        "title": "Indicator 9a: How robust are countries' national public financial management and procurement systems?",
        "subcategories": [],
        "column": "_2014_9a",
        "prefix": "Country Policy and Institutional Assessment (CPIA) score:",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "How reliable is the budget and financial management system (6 is ideal)?",
        "type": "number",
        "precision": "1",
        "footer": "Indicator 9a: Quality of partner countries’ public financial management systems",
        "comparison": "<font color=\"black\">Indicator 9a:</font>Quality of countries’ public financial management systems",
        "partcntry": "_2014_9a",
        "devpart": ""
      },
      {
        "id": "9b",
        "label": "9b: Are development partners using country systems?",
        "title": "Indicator 9b: Are development partners using country systems?",
        "subcategories": [],
        "column": "_2014_9b",
        "prefix": "",
        "suffix": "of development funding disbursements used partner countries' own public financial management and procurement systems.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed using partner countries' own systems",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 9b: Use of partner countries’ own public financial management and procurement systems to deliver development co-operation",
        "comparison": "<font color=\"black\">Indicator 9b:</font> Use of partner countries’ public financial management and procurement systems to deliver development co-operation",
        "partcntry": "_2014_9b_partcntry",
        "devpart": "_2014_9b_devpart"
      },
      {
        "id": "10",
        "label": "10: Is aid untied?",
        "title": "Indicator 10: Is aid untied?",
        "subcategories": [],
        "column": "_2014_10",
        "prefix": "",
        "suffix": "of development funding is untied.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of aid that is fully untied",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 10. Aid is untied",
        "comparison": "<font color=\"black\">Indicator 10:</font> Aid is untied",
        "partcntry": "_2014_10_partcntry",
        "devpart": "_2014_10_devpart"
      }
    ]
  },
  {
    "year": "2016",
    "categories": [
      {
        "id": "1a",
        "label": "1a: Do development partners use countries' own results frameworks and evaluation processes? ",
        "title": "Indicator 1a: Do development partners use partner countries' own results frameworks and evaluation processes?",
        "subcategories": [
          {
            "label": "% of new development interventions that draw their objectives from country-led results frameworks",
            "column": "_2016_1_1",
            "prefix": "",
            "suffix": "of new development interventions draw their objectives from country-led results frameworks.",
            "yesText": "",
            "noText": "",
            "legendText": "% of interventions ",
            "type": "percent",
            "precision": "1",
            "title": "% of new development interventions that draw their objectives from country-led results frameworks (Indicator 1a)",
            "comparison": "% of new development interventions that draw objectives from country-led results frameworks",
            "partcntry": "_2016_1_1_partcntry",
            "devpart": "_2016_1_1_devpart"
          },
          {
            "label": "% of results indicators drawn from country-led results frameworks",
            "column": "_2016_1_2",
            "prefix": "",
            "suffix": "of results indicators are drawn from country-led results frameworks.",
            "yesText": "",
            "noText": "",
            "legendText": "% of results indicators ",
            "type": "percent",
            "precision": "1",
            "title": "% of results indicators drawn from country-led results frameworks (Indicator 1a)",
            "comparison": "% of results indicators drawn from country-led results frameworks",
            "partcntry": "_2016_1_2_partcntry",
            "devpart": "_2016_1_2_devpart"
          },
          {
            "label": "% of results indicators monitored using the partner country's own sources",
            "column": "_2016_1_3",
            "prefix": "",
            "suffix": "of results indicators are monitored using the partner country's own sources and monitoring systems.",
            "yesText": "",
            "noText": "",
            "legendText": "% of results indicators ",
            "type": "percent",
            "precision": "1",
            "title": "% of results indicators monitored using the partner country's own sources (Indicator 1a)",
            "comparison": "% of results indicators monitored using the partner country's own sources",
            "partcntry": "_2016_1_3_partcntry",
            "devpart": "_2016_1_3_devpart"
          },
          {
            "label": "% of new interventions that plan a final evaluation with partner country involvement",
            "column": "_2016_1_4",
            "prefix": "",
            "suffix": "of new interventions that plan a final evaluation with government involvement.",
            "yesText": "",
            "noText": "",
            "legendText": "% of new interventions ",
            "type": "percent",
            "precision": "1",
            "title": "% of new interventions that plan a final evaluation with partner country involvement (Indicator 1a)",
            "comparison": "% of new interventions that plan a final evaluation with partner country involvement",
            "partcntry": "_2016_1_4_partcntry",
            "devpart": "_2016_1_4_devpart"
          }
        ],
        "column": "_2016_1",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 1a: Development partners' use of country-led results frameworks ",
        "comparison": "<font color=\"black\">Indicator 1a:</font> Do development partners use countries' own results frameworks and evaluation processes?",
        "partcntry": "",
        "devpart": ""
      },
      {
        "id": "2",
        "label": "2: Are CSOs engaged in the development effectiveness process?",
        "title": "Indicator 2: Are CSOs engaged in the development effectiveness process?",
        "subcategories": [
          {
            "label": "Do governments support multi-stakeholder dialogue on national development policies?",
            "column": "_2016_2_1",
            "prefix": "Module 1:",
            "suffix": "out of 3 criteria have been met for availability of spaces for multi-stakeholder dialogue on national development policies. ",
            "yesText": "",
            "noText": "",
            "legendText": "Criteria met for 'availability of space for multi-stakeholder dialogue' (3 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Do governments support multi-stakeholder dialogue on national development policies? (Indicator 2)",
            "comparison": "Availabilty of space for multi-stakeholder dialogue on national development policies (3 is ideal)",
            "partcntry": "_2016_2_1",
            "devpart": ""
          },
          {
            "label": "Do CSOs adhere to the development effectiveness principles?",
            "column": "_2016_2_2",
            "prefix": "Module 2:",
            "suffix": "out of 5 criteria have been met for CSO adherence to the development effectiveness principles of co-ordination, accountability and transparency. ",
            "yesText": "",
            "noText": "",
            "legendText": "Criteria met for 'CSOs' own transparency and accountability' (4 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Do CSOs adhere to the development effectiveness principles? (Indicator 2)",
            "comparison": "CSOs apply the principles of accountability and transparency (5 is ideal)",
            "partcntry": "_2016_2_2",
            "devpart": ""
          },
          {
            "label": "Do official development partners co-operate with CSOs?",
            "column": "_2016_2_3",
            "prefix": "Module 3:",
            "suffix": "out of 4 criteria have been met for official development co-operation with CSOs.",
            "yesText": "",
            "noText": "",
            "legendText": "Criteria met for 'official development co-operation with CSOs' (4 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Do official development partners co-operate with CSOs? (Indicator 2)",
            "comparison": "Official development co-operation with CSOs (4 is ideal)",
            "partcntry": "_2016_2_3",
            "devpart": ""
          },
          {
            "label": "How enabling is the legal and regulatory environment for CSOs?",
            "column": "_2016_2_4",
            "prefix": "Module 4:",
            "suffix": "out of 4 criteria have been met for an enabling legal and regulatory environment for CSOs' contribution to development.",
            "yesText": "",
            "noText": "",
            "legendText": "Criteria met for an 'enabling regulatory environment for CSOs' (4 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Is there an enabling legal and regulatory environment for CSOs' engagement in development? (Indicator 2)",
            "comparison": "Legal and regulatory environment in place to maximise CSO engagement (4 is ideal)",
            "partcntry": "_2016_2_4",
            "devpart": ""
          }
        ],
        "column": "_2016_2",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 2: Assessment of an enabling environment for civil society participation in development co-operation ",
        "comparison": "<font color=\"black\">Indicator 2:</font> Are CSOs engaged in the development effectiveness process?",
        "partcntry": "",
        "devpart": ""
      },
      {
        "id": "3",
        "label": "3: What is the quality of public-private dialogue?",
        "title": "Indicator 3: What is the quality of public-private dialogue?",
        "subcategories": [
          {
            "label": "Is the private sector willing to engage in public-private dialogue?",
            "column": "_2016_3_1",
            "prefix": "Private sector willingness to engage in public-private dialogue scored",
            "suffix": "on a scale of 0-10 (10 is ideal).",
            "yesText": "",
            "noText": "",
            "legendText": "Willingness of the private sector to engage in public-private dialogue (10 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Is the private sector willing to engage in public-private dialogue? (Indicator 3)",
            "comparison": "Private sector willingness to engage in public-private dialogue (10 is ideal)",
            "partcntry": "_2016_3_1",
            "devpart": ""
          },
          {
            "label": "Is the government willing to engage in public-private dialogue?",
            "column": "_2016_3_2",
            "prefix": "Government willingness to engage in public-private dialogue scored",
            "suffix": "on a scale of 0-10 (10 is ideal).",
            "yesText": "",
            "noText": "",
            "legendText": "Willingness of the government to engage in public-private dialogue (10 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Is the government willing to engage in public-private dialogue? (Indicator 3)",
            "comparison": "Government willingness to engage in public-private dialogue (10 is ideal)",
            "partcntry": "_2016_3_2",
            "devpart": ""
          },
          {
            "label": "Is there a potential champion who can facilitate public-private dialogue?",
            "column": "_2016_3_3",
            "prefix": "Existence of a potential champion to facilitate public-private dialogue scored",
            "suffix": "on a scale of 0-10 (10 is ideal).",
            "yesText": "",
            "noText": "",
            "legendText": "Existence of champions to facilitate public-private dialogue (10 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Is there a potential champion who can facilitate public-private dialogue? (Indicator 3)",
            "comparison": "Existence of potential champions to facilitate public-private dialogue (10 is ideal)",
            "partcntry": "_2016_3_3",
            "devpart": ""
          },
          {
            "label": "Are instruments available to support public-private dialogue?",
            "column": "_2016_3_4",
            "prefix": "Availability of instruments to facilitate public-private dialogue scored",
            "suffix": "on a scale of 0-10 (10 is ideal).",
            "yesText": "",
            "noText": "",
            "legendText": "Instruments available to facilitate public-private dialogue (10 is ideal)",
            "type": "number",
            "precision": "0",
            "title": "Are instruments available to support public-private dialogue? (Indicator 3)",
            "comparison": "Existence of instruments to support public-private dialogue (10 is ideal)",
            "partcntry": "_2016_3_4",
            "devpart": ""
          }
        ],
        "column": "_2016_3",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 3: Quality of public-private dialogue ",
        "comparison": "<font color=\"black\">Indicator 3:</font> What is the quality of public-private dialogue?",
        "partcntry": "",
        "devpart": ""
      },
      {
        "id": "4",
        "label": "4: Are development partners making high-quality information on development funding publicly accessible?",
        "title": "Indicator 4: Are development partners making high-quality information on development funding publicly accessible?",
        "subcategories": [
          {
            "label": "Assessment of the OECD CRS (backward-looking data for accountability purposes)",
            "column": "_2016_4_1",
            "prefix": "Overall transparency assessment of the OECD Creditor Reporting System providing backward-looking data for accountability purposes:",
            "suffix": "",
            "yesText": "",
            "noText": "",
            "legendText": "How robust are donors' activity-level records of funding?",
            "type": "text",
            "precision": "0",
            "title": "Assessment by the OECD Creditor Reporting System (CRS) - Indicator 4",
            "comparison": "Transparency assessment by the OECD Creditor Reporting System (CRS) - backward-looking data for accountability purposes",
            "partcntry": "",
            "devpart": "_2016_4_1"
          },
          {
            "label": "Assessment of the OECD FSS (data for forecasting purposes)",
            "column": "_2016_4_2",
            "prefix": "Overall transparency assessment of the OECD Forward Spending Survey for forecasting purposes:",
            "suffix": "",
            "yesText": "",
            "noText": "",
            "legendText": "How strong are donors' forward spending plans?",
            "type": "text",
            "precision": "0",
            "title": "Assessment by the OECD Forward Spending Survey (FSS) - Indicator 4 ",
            "comparison": "Transparency assessment by the OECD Forward Spending Survey (FSS) - data for forecasting purposes",
            "partcntry": "",
            "devpart": "_2016_4_2"
          },
          {
            "label": "Assessment of the IATI (data for aid management and planning purposes)",
            "column": "_2016_4_3",
            "prefix": "Overall transparency assessment of the International Aid Transparency Initiative (IATI) for aid management and planning purposes:",
            "suffix": "",
            "yesText": "",
            "noText": "",
            "legendText": "Are donors' reporting information in a timely, comprehensive and forward looking manner?",
            "type": "text",
            "precision": "0",
            "title": "Assessment by the International Aid Transparency Initiative (IATI) - Indicator 4",
            "comparison": "Transparency assessment by the International Aid Transparency Initiative (IATI) - data for aid management and planning purposes",
            "partcntry": "",
            "devpart": "_2016_4_3"
          }
        ],
        "column": "_2016_4",
        "prefix": "",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 4: Transparent information on development co-operation is publicly available",
        "comparison": "<font color=\"black\">Indicator 4:</font> Are development partners making high-quality information on development co-operation publicly accessible?",
        "partcntry": "",
        "devpart": ""
      },
      {
        "id": "5a",
        "label": "5a: How reliable is the disbursement of funding by development partners?",
        "title": "Indicator 5a: How reliable is the disbursement of funding by development partners?",
        "subcategories": [],
        "column": "_2016_5a",
        "prefix": "",
        "suffix": "of development funding was disbursed within the scheduled fiscal year.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed within scheduled fiscal year",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 5a: Annual predictability of development co-operation",
        "comparison": "<font color=\"black\">Indicator 5a:</font> Annual predictability of development co-operation",
        "partcntry": "_2016_5a_partcntry",
        "devpart": "_2016_5a_devpart"
      },
      {
        "id": "5b",
        "label": "5b: Are development partners sharing forward-looking information on planned funding with partner countries?",
        "title": "Indicator 5b: Are development partners sharing forward-looking information on planned funding?",
        "subcategories": [],
        "column": "_2016_5b",
        "prefix": "",
        "suffix": "of development funding was covered by forward spending plans provided by development partners.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding covered by development partners' forward expenditure plans",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 5b: Medium-term predictability of development co-operation",
        "comparison": "<font color=\"black\">Indicator 5b:</font> Medium-term predictability of development co-operation",
        "partcntry": "_2016_5b_partcntry",
        "devpart": "_2016_5b_devpart"
      },
      {
        "id": "6",
        "label": "6: Do partner countries' legislatures have oversight over development funding?",
        "title": "Indicator 6: Do partner countries' legislatures have oversight over development funding?",
        "subcategories": [],
        "column": "_2016_6",
        "prefix": "",
        "suffix": "of development funding scheduled for disbursement was included in national budgets overseen by the legislature.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding included in the partner country's budget ",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 6: Development co-operation is on budgets which are subject to parliamentary scrutiny",
        "comparison": "<font color=\"black\">Indicator 6:</font> Development co-operation is on budgets which are subject to parliamentary scrutiny",
        "partcntry": "_2016_6_partcntry",
        "devpart": "_2016_6_devpart"
      },
      {
        "id": "7",
        "label": "7: Are partner countries conducting inclusive mutual reviews with development partners?",
        "title": "Indicator 7: According to Global Partnership criteria, are partner countries conducting inclusive mutual reviews with development partners?",
        "subcategories": [
          {
            "label": "Is there an aid or partnership policy in place?",
            "column": "_2016_7_1",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 1: An aid or partnership policy is in place.",
            "noText": "Criterion 1: An aid or partnership policy is not in place.",
            "legendText": "Is an aid or partnership policy in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of an aid or partnership policy (Indicator 7)",
            "comparison": "Existence of an aid or partnership policy",
            "partcntry": "_2016_7_1",
            "devpart": ""
          },
          {
            "label": "Have country-level targets for development co-operation been established?",
            "column": "_2016_7_2",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 2: Local targets for development co-operation have been established.",
            "noText": "Criterion 2: Local targets for development co-operation have not been established.",
            "legendText": "Are country-level partnership targets in place?",
            "type": "text",
            "precision": "0",
            "title": "Existence of country-level targets for development co-operation (Indicator 7)",
            "comparison": "Existence of country-level targets for development co-operation",
            "partcntry": "_2016_7_2",
            "devpart": ""
          },
          {
            "label": "Do governments and development partners conduct regular joint assessments towards country-level targets?",
            "column": "_2016_7_3",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 3: Government and development partners conduct regular joint assessment towards targets.",
            "noText": "Criterion 3: Government and development partners do not conduct regular joint assessment towards targets.",
            "legendText": "Are there regular joint assessments among partners?",
            "type": "text",
            "precision": "0",
            "title": "Existence of joint assessments towards country-level targets (Indicator 7)",
            "comparison": "Existence of regular joint assessments between government and development partners",
            "partcntry": "_2016_7_3",
            "devpart": ""
          },
          {
            "label": "Are non-executive stakeholders involved in joint assessments?",
            "column": "_2016_7_4",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 4: Non-executive stakeholders are involved in joint assessments.",
            "noText": "Criterion 4: Non-executive stakeholders are not involved in joint assessments.",
            "legendText": "Are non-executive stakeholders included in joint assessments?",
            "type": "text",
            "precision": "0",
            "title": "Involvement of non-executive stakeholders in joint assessments",
            "comparison": "Involvement of non-executive stakeholders in joint assessments",
            "partcntry": "_2016_7_4",
            "devpart": ""
          },
          {
            "label": "Are joint assessments between government and development partners made public?",
            "column": "_2016_7_5",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 5: Results of joint assessments are made public.",
            "noText": "Criterion 5: Results of joint assessments are not made public.",
            "legendText": "Are joint assessments made public?",
            "type": "text",
            "precision": "0",
            "title": "Publicly-available joint assessments between development partners (Indicator 7)",
            "comparison": "Existence of publicly-available information on joint assessments",
            "partcntry": "_2016_7_5",
            "devpart": ""
          }
        ],
        "column": "_2016_7",
        "prefix": "",
        "suffix": "",
        "yesText": "According to Global Partnership criteria, there is an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria).",
        "noText": "According to Global Partnership criteria, there is not an inclusive, transparent mutual accountability review in place among development partners (the country must be positively assessed on 4/5 of the following criteria).",
        "legendText": "Is a process for inclusive reviews in place?",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 7: Mutual accountability among development partners is strengthened through inclusive reviews",
        "comparison": "<font color=\"black\">Indicator 7:</font> Mutual accountability among development partners is strengthened through inclusive reviews",
        "partcntry": "_2016_7",
        "devpart": ""
      },
      {
        "id": "8",
        "label": "8: Do partner countries track public allocations for gender equality?",
        "title": "Indicator 8: According to Global Partnership criteria, do partner countries track public allocations for gender equality?",
        "subcategories": [
          {
            "label": "Does a government statement establishing a tracking system for gender equality exist?",
            "column": "_2016_8_1",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 1: There is an official government statement defining the system for tracking allocations for gender equality and women's empowerment.",
            "noText": "Criterion 1: There is not an official government statement defining the system for tracking allocations for gender equality and women's empowerment.",
            "legendText": "Is there a government statement on a tracking system for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Existence of a government statement establishing a tracking system for gender equality (Indicator 8)",
            "comparison": "Existence of a government statement establishing a tracking system for gender equality and women's empowerment",
            "partcntry": "_2016_8_1",
            "devpart": ""
          },
          {
            "label": "Are public allocations for gender equality systematically tracked?",
            "column": "_2016_8_2",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 2: Gender allocations are systematically tracked.",
            "noText": "Criterion 2: Gender allocations are not systematically tracked.",
            "legendText": "Is there a government system for tracking allocations for gender equality?",
            "type": "text",
            "precision": "0",
            "title": "Systematic tracking of public allocations for gender equality (Indicator 8)",
            "comparison": "Governments systematically track public allocations for gender equality and women’s empowerment",
            "partcntry": "_2016_8_2",
            "devpart": ""
          },
          {
            "label": "Does a central government unit provide leadership and oversight of a tracking system for gender equality allocations?",
            "column": "_2016_8_3",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 3: There is a central government unit in charge of oversight for tracking allocations for gender equality and women's empowerment.",
            "noText": "Criterion 3: There is not a central government unit in charge of oversight for tracking allocations for gender equality and women's empowerment.",
            "legendText": "Is there a central government unit providing leadership and oversight for gender allocations?",
            "type": "text",
            "precision": "0",
            "title": "Existence of a central government unit to provide leadership and oversight (Indicator 8)",
            "comparison": "A central government unit provides leadership and oversight of a tracking system for gender equality allocations",
            "partcntry": "_2016_8_3",
            "devpart": ""
          },
          {
            "label": "Is gender-equality-focused budget information publicly available?",
            "column": "_2016_8_4",
            "prefix": "",
            "suffix": "",
            "yesText": "Criterion 4: Gender-related budget information is publicly available.",
            "noText": "Criterion 4: Gender-related budget information is not publicly available.",
            "legendText": "Are budget allocations for gender equality publicly available?",
            "type": "text",
            "precision": "0",
            "title": "Public availability of gender-equality-focused budget information (Indicator 8)",
            "comparison": "Existence of pubicly-available information on budget allocations for gender equality",
            "partcntry": "_2016_8_4",
            "devpart": ""
          }
        ],
        "column": "_2016_8",
        "prefix": "",
        "suffix": "",
        "yesText": "According to Global Partnership criteria, there is a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
        "noText": "According to Global Partnership criteria, there is not a system in place for tracking allocations for gender equality and women’s empowerment (the country must be positively assessed for Criteria 1-3 and Criteria 4).",
        "legendText": "Do partner countries track public allocations for gender equality?",
        "type": "text",
        "precision": "0",
        "footer": "Indicator 8: Governments have systems in place to track allocations for gender equality and women’s empowerment",
        "comparison": "<font color=\"black\">Indicator 8:</font> Do countries meet the Global Partnership criteria for tracking public allocations for gender equality and women’s empowerment, and making this information publicly available?",
        "partcntry": "_2016_8",
        "devpart": ""
      },
      {
        "id": "9a",
        "label": "9a: How robust are countries' national public financial management and procurement systems?",
        "title": "9a: How robust are countries' national public financial management and procurement systems?",
        "subcategories": [],
        "column": "_2016_9a",
        "prefix": "Country Policy and Institutional Assessment (CPIA) score:",
        "suffix": "",
        "yesText": "",
        "noText": "",
        "legendText": "How reliable is the budget and financial management system (6 is ideal)?",
        "type": "number",
        "precision": "1",
        "footer": "Indicator 9a: Quality of partner countries’ public financial management systems",
        "comparison": "<font color=\"black\">Indicator 9a:</font> Quality of countries’ public financial management systems",
        "partcntry": "_2016_9a",
        "devpart": ""
      },
      {
        "id": "9b",
        "label": "9b: Are development partners using country systems?",
        "title": "9b: Are development partners using country systems?",
        "subcategories": [],
        "column": "_2016_9b",
        "prefix": "",
        "suffix": "of development co-operation funding disbursed for the government sector used their own public financial management and procurement systems.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of funding disbursed using the countries' own systems",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 9b: Use of partner countries’ own public financial management and procurement systems to deliver development co-operation",
        "comparison": "<font color=\"black\">Indicator 9b:</font> Use of partner countries’ public financial management and procurement systems to deliver development co-operation",
        "partcntry": "_2016_9b_partcntry",
        "devpart": "_2016_9b_devpart"
      },
      {
        "id": "10",
        "label": "10: Is aid untied?",
        "title": "10: Is aid untied?",
        "subcategories": [],
        "column": "_2016_10",
        "prefix": "",
        "suffix": "of development co-operation has been untied.",
        "yesText": "",
        "noText": "",
        "legendText": "Share of aid that is fully untied",
        "type": "percent",
        "precision": "1",
        "footer": "Indicator 10. Aid is untied",
        "comparison": "<font color=\"black\">Indicator 10:</font> Aid is untied",
        "partcntry": "_2016_10_partcntry",
        "devpart": "_2016_10_devpart"
      }
    ]
  }
];