export let devpartner_types = [
 {
  type: "Bilateral partners (DAC members)",
  devpartners: [
   "Australia",
   "Austria",
   "Belgium",
   "Canada",
   "Czech Republic",
   "Denmark",
   "EU Institutions",
   "Finland",
   "France",
   "Germany",
   "Greece",
   "Iceland",
   "Ireland",
   "Italy",
   "Japan",
   "Luxembourg",
   "Netherlands",
   "New Zealand",
   "Norway",
   "Poland",
   "Portugal",
   "Republic of Korea",
   "Slovakia",
   "Slovenia",
   "Spain",
   "Sweden",
   "Switzerland",
   "United Kingdom of Great Britain and Northern Ireland",
   "United States of America",
  ]
 },
 {
  type: "Foundations",
  devpartners: [
   "Aga Khan Development Network",
   "Bill & Melinda Gates Foundation",
   "Carter Center",
   "Christoffel Blindenmission",
   "Global Alliance for Improved Nutrition (GAIN)",
   "Heinrich Boll Foundation",
   "Rosebud Trust, Deakin",
  ]
 },
 {
  type: "Global funds and vertical initiatives",
  devpartners: [
   "Adaptation Fund",
   "African Capacity Building Foundation (ACBF)",
   "Arab Fund",
   "Global Alliance for Vaccines and Immunization (GAVI)",
   "Global Environment Facility (GEF)",
   "Global Fund",
   "Nordic Development Fund (NDF)",
   "OPEC Fund for International Development (OFID)",
   "Pacific Environment Community Fund",
   "Pacific Regional Infrastructure Facility (PRIF)",
   "SAARC Development Fund",
   "South Pacific Regional Environment Program(SPREP)",
  ]
 },
 {
  type: "Multilateral development banks",
  devpartners: [
   "African Development Bank (AfDB)",
   "Arab Bank for Economic Development in Africa (BADEA)",
   "Asian Development Bank (AsDB)",
   "Caribbean Development Bank (CarDB)",
   "Central American Bank for Economic Integration (CABEI)",
   "Council of Europe Development Bank (CEB)",
   "Development Bank of Latin America (CAF)",
   "Economic Community of West African States (ECOWAS)",
   "ECOWAS Bank for Investment and Development (BIDC)",
   "European Bank for Reconstruction and Development (EBRD)",
   "European Investment Bank (EIB)",
   "Inter-American Development Bank (IDB)",
   "International Finance Corporation (IFC)",
   "International Monetary Fund (IMF)",
   "Islamic Development Bank (IsDB)",
   "West African Development Bank (BOAD)",
   "World Bank",
  ]
 },
 {
  type: "Other bilateral partners (non-DAC members)",
  devpartners: [
   "Algeria",
   "Angola",
   "Brazil",
   "China",
   "Colombia",
   "Congo",
   "El Salvador",
   "Equatorial Guinea",
   "Estonia",
   "Gabon",
   "Hungary",
   "India",
   "Iran",
   "Iraq",
   "Kuwait",
   "Latvia",
   "Liechtenstein",
   "Lithuania",
   "Mexico",
   "Monaco",
   "Morocco",
   "Panama",
   "Papua New Guinea",
   "Romania",
   "Russian Federation",
   "Saudi Arabia",
   "Chinese Taipei",
   "Turkey",
   "United Arab Emirates",
  ]
 },
 {
  type: "Other international and regional organisations",
  devpartners: [
   "African Union",
   "Forum Fisheries Agencies",
   "International Atomic Energy Agency (IAEA)",
   "International Organization for Migration (IOM)",
   "International Tropical Timber Organization (ITTO)",
   "International Union for Conservation of Nature (IUCN)",
   "Montreal Protocol",
   "Organization for Security and Co-operation in Europe (OSCE)",
   "Organization of American States (OAS)",
   "Organization of Ibero-American States (OEI)",
   "Pacific Community (SPC)",
   "Saudi Fund for Development (SFD)",
   "Southern African Development Community (SADC)",
   "West African Economic and Monetary Union (UEMOA)",
  ]
 },
 {
  type: "UN agencies",
  devpartners: [
   "Food and Agriculture Organisation (FAO)",
   "International Fund for Agricultural Development (IFAD)",
   "International Labour Organisation (ILO)",
   "UN Agencies (not specified)",
   "UN Habitat",
   "UN Joint Programme on Local Governance (JPLG)",
   "UN Mine Action Service (UNMAS)",
   "UN Peacebuilding Fund (UNPBF)",
   "UN Volunteers",
   "UN Women",
   "UNAIDS",
   "UNESCO",
   "United Nation Development Cooperation Forum (UNDCF)",
   "United Nations Central Emergency Response Fund (CERF)",
   "United Nations Children's Fund (UNICEF)",
   "United Nations Conference on Trade and Development (UNCTAD)",
   "United Nations Development Programme (UNDP)",
   "United Nations Economic Commission for Europe (UNECE)",
   "United Nations Environment Programme (UNEP)",
   "United Nations High Commissioner for Refugees (UNHCR)",
   "United Nations Industrial Development Organization (UNIDO)",
   "United Nations Office for Project Services (UNOPS)",
   "United Nations Office on Drugs and Crime (UNODC)",
   "United Nations Operation in Côte d’Ivoire (UNOCI)",
   "United Nations Population Fund (UNFPA)",
   "World Food Programme (WFP)",
   "World Health Organisation (WHO)",
  ]
 },
];